user www-data www-data;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
error_log /dev/stdout notice;
pid /var/run/nginx.pid;
worker_rlimit_nofile 51200;

events {
    use epoll;
    worker_connections 5120;
    multi_accept on;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    access_log /dev/stdout main;

    server_tokens off;
    ignore_invalid_headers on;
    underscores_in_headers off;
    client_header_timeout 15s;
    client_body_timeout 120s;
    client_header_buffer_size 8k;
    large_client_header_buffers 4 16k;
    client_max_body_size 100m;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 30s;
    keepalive_requests 1000;

    server_names_hash_bucket_size 512;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 2;
    gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/json;
    gzip_vary on;
    gzip_proxied expired no-cache no-store private auth;
    gzip_disable "MSIE [1-6]\.";

    limit_conn_zone $binary_remote_addr zone=perip:10m;
    limit_conn_zone $server_name zone=perserver:10m;

    map $http_upgrade $tsukuyomi_connection_upgrade {
        default upgrade;
        '' close;
    }

    include /usr/local/openresty/nginx/conf/conf.d/*.conf;
    include /usr/local/openresty/nginx/conf/default/*.conf;
}

stream {
    log_format streamlog '$remote_addr[$time_local] '
                         '$protocol $status $bytes_sent $bytes_received '
                         '$session_time';
    access_log /var/log/nginx/stream-access.log streamlog;
    access_log /dev/stdout streamlog;

    include /usr/local/openresty/nginx/conf/stream.d/*.conf;
}
